### PR TITLE
Update nightowl.xml

### PR DESCRIPTION
**Pull request by mallowigi**
Adding accentcolor and excludedcolor

### CODE REVIEW

**Comment by xdrop** [comment]
I was always wondering why that never worked, thanks! 😅 

Do I still need these lines under `<colors>`? @mallowigi 
```
<color id="accentColor" value="E91E63"/>
<color id="accent" value="E91E63"/>
```

**Comment by mallowigi** [comment]
No, as you can see the accentColor was moved in the mtTheme properties

**Comment by xdrop** [comment]
@mallowigi Is there any way to avoid this breaking installations for people who haven't yet updated to `2.6.0`?

 For example someone who hasn't updated to `2.6.0` doing this change will cause the plugin to fail to load during the xstream deserialization.

`No such field com.chrisrm.idea.themes.models.MTLightBundledTheme.accentColor`

**Comment by mallowigi** [comment]
No I don't think there is, but I will try to do retrocompatibility support. Thanks

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&utm_medium=email&utm_campaign=sent-from-mailbird]
On 29-Jul-18 6:19:58 PM, Panayiotis <notifications@github.com> wrote:
@mallowigi [https://github.com/mallowigi] Is there any way to avoid this breaking installations for people who haven't yet updated to 2.6.0?
For example someone who hasn't updated to 2.6.0 doing this change will cause the plugin to fail to load during the xstream deserialization.
No such field com.chrisrm.idea.themes.models.MTLightBundledTheme.accentColor

**Comment by mallowigi** [comment]
I've updated the 2018.1 branch to support partially the properties, but that's the most that I can do. People that are using an older version of the plugin because they use 2017.X or older versions of 2018.1 will not be able to get the feature. As for people still on an older version of the plugin should update it.

You can also deliver a version of your plugin without a dependency to Material Theme, so that people not being able to use your plugin would still get the color scheme.

**Comment by xdrop** [comment]
@mallowigi Thanks, I will add a notification for when users are using an incompatible version so that they know to update, and release colour scheme version only for pre 2018.1

**Pull request merged**
