### PR TITLE
Make this plugin available for IDE above 2017.2 & Bump rainbow brackets version

### PR DESCRIPTION
**Pull request by izhangzhihao**

### CODE REVIEW

**Comment by xdrop** [comment]
Thanks, that was on my list of things to do 🙂

**Comment by xdrop** [comment]
Actually might have to bump the version a bit higher as the external theme extension points I'm using from material theme jetbrains were [added in version 2](https://github.com/ChrisRM/material-theme-jetbrains#external-themes) so I guess [181.3494.1](https://plugins.jetbrains.com/plugin/8006-material-theme-ui/update/44268) is the minimum.

**Comment by izhangzhihao** [comment]
It seems avaliable(for color scheme at least): 
screen shot 2018-07-22 at 6 10 31 pm

**Comment by xdrop** [comment]
Interesting, which version is that?

Also, I've asked at https://github.com/ChrisRM/material-theme-jetbrains/issues/852 they said it should work 2018.1+, but might need to start developing for 2018.2 which is gonna be out quite soon because they refactored some stuff

**Comment by izhangzhihao** [comment]
```
IntelliJ IDEA 2017.2
Build #IC-172.3317.76, built on July 15, 2017
JRE: 1.8.0_144-b01 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Mac OS X 10.13.6
```

**Comment by xdrop** [comment]
That might be because the color scheme extension is an `intellij` extension point rather than a material theme ui one:
```
    <extensions defaultExtensionNs="com.intellij">
        <bundledColorScheme path="colors/NightOwl" id="Night Owl"/>
    </extensions>
```

Can you check if you able to switch the Material Theme External Theme option to Night Owl to color the overall UI? (Tools > Material Theme > Material Theme Chooser > External Themes > Night Owl Theme)

**Comment by izhangzhihao** [comment]
screen shot 2018-07-22 at 6 59 26 pm

**Comment by xdrop** [comment]
Ok that makes sense then you can't get the overall ui theme in 2017.2.

In that case we could do separate releases, one targeting 2017.2+ for just the bundled color scheme, one for targeting 2018.1+ for the external theme plus the color scheme and one for 2018.2+ to support the latest Material Theme

**Comment by izhangzhihao** [comment]
Good point!

**Comment by NMinhNguyen** [comment]
For what it's worth, 2018.2 is out :)

**Comment by xdrop** [comment]
@NMinhNguyen Thanks, I'll try and get an updated pushed today.

**Pull request merged**
